import React, { useMemo } from 'react';
import { useData } from '../contexts/DataContext';
import { useAuth } from '../contexts/AuthContext';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line } from 'recharts';
import { TrendingUp, Share2, Printer, FileText, DollarSign, ArrowDownRight, ArrowUpRight, Package, FileSpreadsheet } from 'lucide-react';
import { UserRole } from '../types';

const Reports = () => {
  const { transactions, products, branches } = useData();
  const { activeBranchId, user } = useAuth();

  // STRICT DATA ISOLATION
  // Determines the scope of data to show: specific branch ID or null for global view (Owners/Managers only)
  const effectiveBranchId = user?.role === UserRole.PHARMACIST 
      ? user.assignedBranchId 
      : activeBranchId;

  const currentBranchName = effectiveBranchId 
      ? branches.find(b => b.id === effectiveBranchId)?.name 
      : "All Branches";

  // Filter Data based on Effective Branch
  const filteredTransactions = useMemo(() => {
    if (user?.role === UserRole.PHARMACIST && !effectiveBranchId) return [];
    
    return effectiveBranchId 
      ? transactions.filter(t => t.branchId === effectiveBranchId)
      : transactions;
  }, [transactions, effectiveBranchId, user]);

  // Calculate Financials (Revenue, COGS, Profit)
  const financials = useMemo(() => {
      let revenue = 0;
      let cogs = 0;

      filteredTransactions.forEach(t => {
          revenue += t.totalAmount;
          t.items.forEach(item => {
              // Find original product to get Cost Price
              // If product is deleted, fallback to 70% of selling price as estimated cost
              const product = products.find(p => p.id === item.productId);
              const cost = product ? product.costPrice : (item.price * 0.7);
              cogs += (cost * item.quantity);
          });
      });

      const grossProfit = revenue - cogs;
      const margin = revenue > 0 ? (grossProfit / revenue) * 100 : 0;

      return { revenue, cogs, grossProfit, margin };
  }, [filteredTransactions, products]);

  // Chart Data
  const dailySalesData = useMemo(() => {
    const last7Days = [...Array(7)].map((_, i) => {
        const d = new Date();
        d.setDate(d.getDate() - (6 - i));
        return d.toISOString().split('T')[0];
    });

    return last7Days.map(date => {
        const dayTxns = filteredTransactions.filter(t => t.date.startsWith(date));
        const dayRevenue = dayTxns.reduce((sum, t) => sum + t.totalAmount, 0);
        // Estimate profit for chart
        const dayProfit = dayRevenue * (financials.margin / 100 || 0.3); 
        
        return { 
            date: date.slice(5), 
            revenue: dayRevenue,
            profit: dayProfit
        };
    });
  }, [filteredTransactions, financials.margin]);

  const topProducts = useMemo(() => {
    const stats: Record<string, { qty: number, rev: number }> = {};
    filteredTransactions.forEach(t => {
        t.items.forEach(i => {
            if (!stats[i.name]) stats[i.name] = { qty: 0, rev: 0 };
            stats[i.name].qty += i.quantity;
            stats[i.name].rev += (i.quantity * i.price);
        });
    });
    return Object.entries(stats)
        .sort((a, b) => b[1].qty - a[1].qty)
        .slice(0, 5)
        .map(([name, stat]) => ({ name, quantity: stat.qty, revenue: stat.rev }));
  }, [filteredTransactions]);

  const handleWhatsAppShare = () => {
      const date = new Date().toLocaleDateString();
      
      const text = `*📊 PRO FORMA PROFIT & LOSS STATEMENT*
*Nexile Pharmacy OS*

📅 *Date:* ${date}
📍 *Branch:* ${currentBranchName || 'N/A'}
👤 *Generated By:* ${user?.name}

*REVENUE SUMMARY*
━━━━━━━━━━━━━━━━━━━━━
💵 *Total Revenue:*  $${financials.revenue.toFixed(2)}
📉 *COGS:*           $${financials.cogs.toFixed(2)}
━━━━━━━━━━━━━━━━━━━━━
💰 *NET PROFIT:*     $${financials.grossProfit.toFixed(2)}
📊 *NET MARGIN:*     ${financials.margin.toFixed(1)}%

*TOP MOVERS (Qty)*
${topProducts.slice(0, 3).map((p, i) => `${i+1}. ${p.name}: ${p.quantity}`).join('\n')}

_Sent via Nexile Pharmacy OS_`;
      
      const encodedText = encodeURIComponent(text);
      window.open(`https://wa.me/?text=${encodedText}`, '_blank');
  };

  const handlePrint = () => {
      window.print();
  };

  const handleExportCSV = () => {
    const headers = ['Transaction ID', 'Date', 'Items', 'Total Amount', 'Payment Method', 'Branch'];
    const rows = filteredTransactions.map(t => [
        t.id,
        new Date(t.date).toLocaleDateString(),
        t.items.map(i => `${i.quantity}x ${i.name}`).join('; '),
        t.totalAmount.toFixed(2),
        t.paymentMethod,
        branches.find(b => b.id === t.branchId)?.name || t.branchId
    ]);
    
    const csvContent = [
        headers.join(','),
        ...rows.map(r => r.map(c => `"${c}"`).join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `nexile_report_${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
  };

  return (
    <div className="p-6 space-y-6 animate-fade-in overflow-y-auto h-full pb-24 print:p-0 print:bg-white print:text-black print:overflow-visible">
      <div className="flex flex-col sm:flex-row items-center justify-between gap-4 print:hidden">
        <div>
            <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Reports & Analytics</h1>
            <p className="text-slate-500 dark:text-slate-400 text-sm">
                Financial performance for <span className="font-bold">{currentBranchName}</span>.
            </p>
        </div>
        <div className="flex flex-wrap gap-3">
            <button onClick={handleWhatsAppShare} className="flex items-center gap-2 px-4 py-2 bg-[#25D366] text-white rounded-lg text-sm font-bold hover:bg-[#128C7E] transition-colors shadow-sm active:scale-95">
                <Share2 size={16} /> Share WhatsApp
            </button>
            <button onClick={handleExportCSV} className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-bold hover:bg-blue-700 transition-colors shadow-sm active:scale-95">
                <FileSpreadsheet size={16} /> Export CSV
            </button>
            <button onClick={handlePrint} className="flex items-center gap-2 px-4 py-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-lg text-sm font-medium text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
                <Printer size={16} /> Save PDF
            </button>
        </div>
      </div>

      {/* Profit & Loss Statement Card */}
      <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden print:border-2 print:border-black print:mb-8 print:shadow-none">
        <div className="p-6 border-b border-slate-100 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-800/50 flex justify-between items-center">
            <div>
                <h3 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
                    <FileText size={20} className="text-nexile-600"/> Profit & Loss Statement
                </h3>
                <p className="text-xs text-slate-500 print:text-black">Generated on {new Date().toLocaleDateString()}</p>
            </div>
            <div className="text-right hidden print:block">
                <h2 className="text-xl font-bold">Nexile Pharmacy</h2>
                <p className="text-sm text-slate-500">{effectiveBranchId ? currentBranchName : 'Consolidated Report'}</p>
            </div>
        </div>
        
        <div className="p-6 grid grid-cols-1 md:grid-cols-3 gap-8">
            {/* Revenue Section */}
            <div className="space-y-1">
                <p className="text-sm font-medium text-slate-500 uppercase tracking-wider">Total Revenue</p>
                <h2 className="text-3xl font-bold text-slate-900 dark:text-white print:text-black">${financials.revenue.toFixed(2)}</h2>
                <div className="flex items-center gap-1 text-xs text-green-600">
                    <ArrowUpRight size={14} /> Gross Sales
                </div>
            </div>

            {/* COGS Section */}
            <div className="space-y-1">
                <p className="text-sm font-medium text-slate-500 uppercase tracking-wider">Cost of Goods Sold</p>
                <h2 className="text-3xl font-bold text-slate-900 dark:text-white print:text-black">${financials.cogs.toFixed(2)}</h2>
                <div className="flex items-center gap-1 text-xs text-red-500">
                    <ArrowDownRight size={14} /> Inventory Cost
                </div>
            </div>

            {/* Net Profit Section */}
            <div className="space-y-1 relative">
                <div className="absolute -left-4 top-0 bottom-0 w-px bg-slate-200 dark:bg-slate-700 md:block hidden"></div>
                <p className="text-sm font-medium text-slate-500 uppercase tracking-wider">Net Profit</p>
                <h2 className={`text-3xl font-bold ${financials.grossProfit >= 0 ? 'text-green-600 dark:text-green-400' : 'text-red-600'} print:text-black`}>
                    ${financials.grossProfit.toFixed(2)}
                </h2>
                <div className="flex items-center gap-1 text-xs text-slate-400">
                    <DollarSign size={14} /> {financials.margin.toFixed(1)}% Margin
                </div>
            </div>
        </div>

        {/* Added Top Products Section to Report */}
        <div className="px-6 pb-6 pt-2 border-t border-slate-100 dark:border-slate-800 mt-2">
             <h4 className="text-sm font-medium text-slate-500 mb-4 uppercase tracking-wider flex items-center gap-2">
                <Package size={16} /> Top 3 Performing Products
             </h4>
             <div className="space-y-3">
                {topProducts.slice(0, 3).map((product, idx) => (
                    <div key={idx} className="flex justify-between items-center text-sm p-2 rounded hover:bg-slate-50 dark:hover:bg-slate-800/50 print:bg-transparent print:p-0">
                         <div className="flex items-center gap-3">
                             <span className="font-mono text-slate-400 w-4">0{idx + 1}</span>
                             <span className="font-medium text-slate-900 dark:text-white print:text-black">{product.name}</span>
                         </div>
                         <div className="text-right flex items-center gap-4">
                             <span className="font-bold text-slate-900 dark:text-white print:text-black">{product.quantity} sold</span>
                             <span className="text-xs text-slate-500 print:text-gray-600 w-24">${product.revenue.toFixed(2)} rev</span>
                         </div>
                    </div>
                ))}
                {topProducts.length === 0 && <p className="text-slate-400 text-sm italic">No sales data available to determine top performers.</p>}
             </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 print:block print:space-y-6">
        {/* Revenue Chart */}
        <div className="bg-white dark:bg-slate-900 p-6 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm print:border print:shadow-none print:break-inside-avoid">
            <h3 className="font-bold text-slate-900 dark:text-white mb-6 print:text-black">Revenue vs Profit (7 Days)</h3>
            <div className="h-64 w-full">
                <ResponsiveContainer width="100%" height="100%">
                    <LineChart data={dailySalesData}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#334155" opacity={0.1} />
                        <XAxis dataKey="date" stroke="#94a3b8" fontSize={12} tickLine={false} axisLine={false} />
                        <YAxis stroke="#94a3b8" fontSize={12} tickLine={false} axisLine={false} tickFormatter={(value) => `$${value}`}/>
                        <Tooltip 
                            contentStyle={{ backgroundColor: '#1e293b', borderColor: '#334155', color: '#fff' }} 
                            itemStyle={{ color: '#fff' }}
                        />
                        <Line type="monotone" dataKey="revenue" name="Revenue" stroke="#0d9488" strokeWidth={3} dot={{r: 4, fill: '#0d9488'}} activeDot={{r: 6}} />
                        <Line type="monotone" dataKey="profit" name="Profit" stroke="#3b82f6" strokeWidth={3} dot={{r: 4, fill: '#3b82f6'}} />
                    </LineChart>
                </ResponsiveContainer>
            </div>
        </div>

        {/* Top Products Chart */}
        <div className="bg-white dark:bg-slate-900 p-6 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm print:border print:shadow-none print:break-inside-avoid">
             <h3 className="font-bold text-slate-900 dark:text-white mb-6 print:text-black">Top Selling Items by Qty</h3>
             <div className="h-64 w-full">
                <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={topProducts} layout="vertical">
                        <CartesianGrid strokeDasharray="3 3" stroke="#334155" opacity={0.1} horizontal={true} vertical={false} />
                        <XAxis type="number" stroke="#94a3b8" fontSize={12} hide />
                        <YAxis dataKey="name" type="category" stroke="#94a3b8" fontSize={12} tickLine={false} axisLine={false} width={100} />
                        <Tooltip 
                             cursor={{fill: 'transparent'}}
                             contentStyle={{ backgroundColor: '#1e293b', borderColor: '#334155', color: '#fff' }} 
                        />
                        <Bar dataKey="quantity" fill="#0d9488" radius={[0, 4, 4, 0]} barSize={32} />
                    </BarChart>
                </ResponsiveContainer>
            </div>
        </div>
      </div>

      {/* Detailed Table */}
      <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden print:border print:shadow-none print:mt-8">
        <div className="p-6 border-b border-slate-200 dark:border-slate-800 print:border-b-black">
            <h3 className="font-bold text-slate-900 dark:text-white print:text-black">Transaction Ledger</h3>
        </div>
        <table className="w-full text-left text-sm">
            <thead className="bg-slate-50 dark:bg-slate-950 text-slate-500 print:bg-gray-100 print:text-black">
                <tr>
                    <th className="px-6 py-3">ID</th>
                    <th className="px-6 py-3">Date</th>
                    <th className="px-6 py-3">Items</th>
                    <th className="px-6 py-3">Amount</th>
                    <th className="px-6 py-3">Method</th>
                </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800 print:divide-gray-200">
                {filteredTransactions.slice(0, 15).map(t => (
                    <tr key={t.id}>
                        <td className="px-6 py-3 font-mono text-xs text-slate-500">{t.id.split('-')[1] || t.id}</td>
                        <td className="px-6 py-3 text-slate-700 dark:text-slate-300 print:text-black">{new Date(t.date).toLocaleDateString()}</td>
                        <td className="px-6 py-3 text-slate-700 dark:text-slate-300 print:text-black">{t.items.length} items</td>
                        <td className="px-6 py-3 font-medium text-slate-900 dark:text-white print:text-black">${t.totalAmount.toFixed(2)}</td>
                        <td className="px-6 py-3">
                            <span className="px-2 py-1 rounded bg-slate-100 dark:bg-slate-800 text-xs text-slate-500 print:border print:border-gray-300">{t.paymentMethod}</span>
                        </td>
                    </tr>
                ))}
                {filteredTransactions.length === 0 && (
                    <tr>
                        <td colSpan={5} className="px-6 py-8 text-center text-slate-400">
                            {effectiveBranchId 
                                ? `No transactions found for ${currentBranchName}.` 
                                : "No transactions found in the system."}
                        </td>
                    </tr>
                )}
            </tbody>
        </table>
      </div>

      <div className="hidden print:block mt-12 pt-8 border-t border-gray-300 text-center text-xs text-gray-500">
          <p>Nexile Pharmacy OS - Confidential Financial Report</p>
          <p>Generated by {user?.name} on {new Date().toLocaleString()}</p>
      </div>
    </div>
  );
};

export default Reports;